export interface DataUserC {
  fecha_expedicion_cedula: String,
  lugar_expedicion_cedula: String,
  pais: String,
  departamento: String,
  ciudad: String,
  direccion: String,
  telefono_1: String,
  fecha_nacimiento: String,
  lugar_nacimiento: String,
  nombre_arl: String,
  nombre_eps: String,
  numero_licencia_conducir: Number,
  categoria_licencia: String,
  vencimiento_licencia: String,
  tipo_sangre: String,
  genero: String,
  ref_nombre1: String,
  ref_empresa1: String,
  ref_telefono1: Number,
  ref_nombre2: String,
  ref_empresa2: String,
  ref_telefono2: Number,
  ref_nombre3: String,
  ref_empresa3: String,
  ref_telefono3: Number,
  req_fletes: Number,
  req_disponibilidad: Number,
  req_cargas: Number

}
